[package]
name = "rust_asm_demo"
version = "0.1.0"
edition = "2024"

[dependencies]

[lib]
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "demo"
path = "src/main.rs"

[build-dependencies]
cc = "1.2.51"
